### ISSUE TITLE
Need to set an offset while there is a fixed header on the page

### ISSUE THREAD

**Issue by showhan** [vursen/FloatSidebar.js#15]
Thanks for the nice extension. Adding an offset option to start the scroll triggering from that offset position would be a great addition. Currently, it works with `window` as the viewport; if we could add an offset to move down the scroll target position, it could be implemented easily with a fixed header.

Thanks

**Comment by vursen** [comment]
Hello @showhan! 

I apologize for the late reply. This ticket somehow escaped my attention.

Could you please elaborate on it? I'm not sure I understood your request. There are already `topSpacing` and `bottomSpacing` options. Don't they work for you?

**Comment by showhan** [comment]
Sorry @vursen, for the delay! I actually forgot the actual issue of what it was exactly for; hence I need to explore it again to find it out. By the way, I will close the topic, and if I need it again, I can open it further with more details.

Thanks for your message!
