### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by blackcoat77** [vursen/FloatSidebar.js#2]
Just to thank you for your wonderful script. It helped me a lot. I'm getting a Uncaught TypeError in dev console at line: 396 (   `var $sideInner = options.sidebarInner || $sideOuter.firstElementChild; `) 

When I hover over the error it says: _Uncaught TypeError: Cannot read property 'firstElementChild' of null_.

Although your script works as expected. 

Any thoughts?

Thanks

**Comment by vursen** [comment]
Hi, @blackcoat77. Thanks for your feedback. I need more details. 

What is your html layout?  

How do you initialize plugin?

**Comment by blackcoat77** [comment]
Hi @vursen, Sorry for the late reply. I apologize, it was my mistake, I didn't properly enqueue in Wordpress. Everything works well. Thank you very much. 

Cheers!
